version: '3'
services:
  php-workspace:
    build: ./php
    volumes:
      - ./code:/var/www/html
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx
    volumes:
      - ./log/nginx:/var/log/nginx/
    ports:
      - "8080:8080"
    depends_on:
      - php-workspace
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:5.0.5-alpine